config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
 validates :content, presence: true, length: { maximum: 255 }
 validates :status, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  def index
    @task = Task.all.page(params[:page]).per(15)
  end
  
  def show
    @task = Task.find(params[:id])
  end
  
  def new
    @task = Task.new
  end
  
  def update
    @task = Task.find(params[:id])
    
    if @task.update(task_params)
      flash[:success] = 'タスクは正常に更新されました。'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクは更新されませんでした。'
      render :edit
    end
  end
  
  def create
    @task = Task.new(task_params)
    
    if @task.save
      flash[:success] = 'タスクが追加されました。'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクが追加されませんでした。'
      render :new
    end
  end
  
  def edit
    @task = Task.find(params[:id])
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    
    flash[:success] = 'タスクは正常に削除されました。'
    redirect_to tasks_url
  end

  private
  
  # Strong Parameter
  def set_task
    @task = Task.find(params[:id])
  end
    
  
  def task_params
    params.require(:task).permit(:content, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task_instance| %>
    <div class="alert alert-<%= task_type %>">
      <%= task_instance %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TaskList</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to  '新規タスクの追加', new_task_path %>
            </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_tasks' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 ">
    <%= form_for(task) do |task_instance| %>
    
      <% if task.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
  
      <div class="form-group">
        <%= task_instance.label :content, 'タスク名' %>
        <%= task_instance.text_field :content, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= task_instance.label :status, '状態' %>
        <%= task_instance.text_field :status, class: 'form-control' %>
      </div>

      <%= task_instance.submit '確定', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>id: <% @task.id %>のタスク編集ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', task_path, class: "btn btn-link" %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<% if @task.any? %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>No.</th>
        <th>タスク名</th>
        <th>状態</th>
      </tr>
    </thead>
    
    <tbody>
      <% @task.each do |task_instance| %>
        <tr>
          <td>
            <%= link_to task_instance.id, task_instance %>
          </td>
          <td>
            <%= task_instance.content %>
          </td>
          <td>
            <%= task_instance.status %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <div>
    <%= paginate @task %>
  </div>
<% end %>

<%= link_to 'タスクを追加する', new_task_path, class: "btn btn-primary" %>

app/views/tasks/new.html.erb
<h1>タスク追加ページ</h1>

<%= render 'form', task: @task %>

<br>
<%= link_to 'タスク一覧に戻る', tasks_path, class: "btn btn-link" %>

app/views/tasks/show.html.erb
<h1>id = <%= @task.id %>のタスク詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>No.</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>タスク名</th>
    <td><%= @task.content %></td>
  </tr>
  <tr>
    <th>状態</th>
    <td><%= @task.status %></td>
  </tr>
</table>

<%= link_to 'このタスクを編集する', edit_task_path(@task), class: "btn btn-primary" %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data:{confirm: '本当に削除してよろしいですか?'}, class: "btn btn-danger" %>

<br>
<%= link_to 'タスク一覧に戻る', tasks_path, class: "btn btn-link" %>